<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Password</name>
   <tag></tag>
   <elementGuidId>56122e68-77fe-42fe-b9fb-cc2c4698dc8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;Password&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//input[count(. | //*[@maxlength = '50']) = count(//*[@maxlength = '50'])][count(. | //*[@class = 'form-control']) = count(//*[@class = 'form-control'])][count(. | //*[@data-val = 'true']) = count(//*[@data-val = 'true'])][count(. | //*[@data-val-length = 'The Password should not exceed 20 characters.']) = count(//*[@data-val-length = 'The Password should not exceed 20 characters.'])][count(. | //*[@data-val-length-max = '14']) = count(//*[@data-val-length-max = '14'])][count(. | //*[@data-val-maxlength = 'The field Password must be a string or array type with a maximum length of '14'.']) = count(//*[@data-val-maxlength = 'The field Password must be a string or array type with a maximum length of '14'.'])][count(. | //*[@data-val-maxlength-max = '14']) = count(//*[@data-val-maxlength-max = '14'])][count(. | //*[@data-val-required = 'Password is mandatory.']) = count(//*[@data-val-required = 'Password is mandatory.'])][count(. | //*[@for = 'Password']) = count(//*[@for = 'Password'])][count(. | //*[@id = 'Password']) = count(//*[@id = 'Password'])][count(. | //*[@name = 'Password']) = count(//*[@name = 'Password'])][count(. | //*[@placeholder = 'password']) = count(//*[@placeholder = 'password'])][count(. | //*[@type = 'password']) = count(//*[@type = 'password'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>The Password should not exceed 20 characters.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>14</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength</name>
      <type>Main</type>
      <value>The field Password must be a string or array type with a maximum length of '14'.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-maxlength-max</name>
      <type>Main</type>
      <value>14</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Password is mandatory.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Password&quot;)</value>
   </webElementProperties>
</WebElementEntity>
