<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>figure_profile-userpic</name>
   <tag></tag>
   <elementGuidId>7a940acd-40b4-45ff-afe8-b2232560c49e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//figure</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;sidemenu&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>figure</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>profile-userpic</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;profile&quot;)/figure[@class=&quot;profile-userpic&quot;]</value>
   </webElementProperties>
</WebElementEntity>
